### ISSUE TITLE
数据库连接失败

### ISSUE THREAD

**Issue by thenan157** [kiwijang/2020_msgboard#1]

**Comment by kiwijang** [comment]
@thenan157  嗨 
conn.php 要設定你自己本機的 db 資訊喔~
因為資安問題所以不會把這些隱密的資料推到公開網路上，如果你練習完要保存一份到網路，記得要把那些本機資料清掉~

**Comment by thenan157** [comment]
![IMG_20231223_173342](https://github.com/kiwijang/2020_msgboard/assets/154507005/6cc32a4e-f43a-4e8b-9aa8-3d727d42de81)
他报错了

**Comment by kiwijang** [comment]
@thenan157  覺得是 php 版本問題，我剛好沒有記錄版號orz
可以試試看用 php 7？
不然試試把整段問題貼給 chatgpt debug 看看
